include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/generated_plugin_registrant.dart"

  errors:
    invalid_annotation_target: ignore
  
  plugins:
    - custom_lint
